name 'olyn_init'
maintainer 'Scott Richardson'
maintainer_email 'dev@grogwood.com'
chef_version '~> 16'
license 'GPL-3.0'
supports 'debian', '>= 10'
source_url 'https://gitlab.com/olyn/olyn_init'
description 'Configures Olyn'
version '1.0.3'

provides 'olyn_init::default'
recipe 'olyn_init::default', 'Configures Olyn'
recipe 'olyn_init::secret_key_file', 'Configures secret key file'
