name 'olyn_init'
maintainer 'Scott Richardson'
maintainer_email 'dev@grogwood.com'
chef_version '~> 16'
license 'GPL-3.0'
supports 'debian', '>= 10'
source_url 'https://gitlab.com/olyn/olyn_init'
description 'Configures Olyn'
version '1.1.2'

provides 'olyn_init::default'
provides 'olyn_init::application_data'
provides 'olyn_init::berkshelf'
provides 'olyn_init::secret_key_file'
recipe 'olyn_init::default', 'Configures Olyn'
recipe 'olyn_init::application_data', 'Configures application data directory'
recipe 'olyn_init::berkshelf', 'Configurations for Berkshelf'
recipe 'olyn_init::secret_key_file', 'Configures secret key file'

gem 'berkshelf'
